services:
  - type: web
    name: dress-up-blind-box
    env: python
    buildCommand: pip install --only-binary :all: -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true